### ISSUE TITLE
Unsupported array element type io.trino.spi.type.DateType

### ISSUE THREAD

**Issue by aleksanderlech** [nineinchnick/trino-openapi#124]
**Versions affected:** 1.60-SNAPSHOT

It seems that the following method of `JsonTrinoConverter`

```java
private static void writeTo(BlockBuilder rowBuilder, Object value, Type type) {}
```

is missing handling of `io.trino.spi.type.DateType` type. 

**Full stacktrace:**

```
java.lang.RuntimeException: Unsupported array element type io.trino.spi.type.DateType
	at pl.net.was.JsonTrinoConverter.writeTo(JsonTrinoConverter.java:271)
	at pl.net.was.JsonTrinoConverter.lambda$writeRow$3(JsonTrinoConverter.java:206)
	at java.base/java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104)
	at java.base/java.util.stream.IntPipeline$Head.forEach(IntPipeline.java:617)
	at pl.net.was.JsonTrinoConverter.lambda$writeRow$4(JsonTrinoConverter.java:201)
	at io.trino.spi.block.RowBlockBuilder.buildEntry(RowBlockBuilder.java:111)
	at pl.net.was.JsonTrinoConverter.writeRow(JsonTrinoConverter.java:198)
	at pl.net.was.JsonTrinoConverter.convert(JsonTrinoConverter.java:147)
	at pl.net.was.JsonTrinoConverter.lambda$writeRow$3(JsonTrinoConverter.java:205)
	at java.base/java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104)
	at java.base/java.util.stream.IntPipeline$Head.forEach(IntPipeline.java:617)
	at pl.net.was.JsonTrinoConverter.lambda$writeRow$4(JsonTrinoConverter.java:201)
	at io.trino.spi.block.RowBlockBuilder.buildEntry(RowBlockBuilder.java:111)
	at pl.net.was.JsonTrinoConverter.writeRow(JsonTrinoConverter.java:198)
	at pl.net.was.JsonTrinoConverter.convert(JsonTrinoConverter.java:147)
	at pl.net.was.OpenApiClient.convertJsonToRecords(OpenApiClient.java:547)
	at pl.net.was.OpenApiClient.convertJson(OpenApiClient.java:480)
	at pl.net.was.OpenApiClient$JsonResponseHandler.handle(OpenApiClient.java:465)
	at pl.net.was.OpenApiClient$JsonResponseHandler.handle(OpenApiClient.java:428)
	at io.airlift.http.client.jetty.JettyHttpClient.doExecute(JettyHttpClient.java:759)
	at io.airlift.http.client.jetty.JettyHttpClient.execute(JettyHttpClient.java:672)
	at pl.net.was.OpenApiClient.makeRequest(OpenApiClient.java:219)
	at pl.net.was.OpenApiClient.getRows(OpenApiClient.java:133)
	at pl.net.was.OpenApiRecordSetProvider.getRecordSet(OpenApiRecordSetProvider.java:74)
	at io.trino.split.RecordPageSourceProvider.createPageSource(RecordPageSourceProvider.java:50)
	at io.trino.split.PageSourceManager$PageSourceProviderInstance.createPageSource(PageSourceManager.java:79)
	at io.trino.operator.TableScanOperator.getOutput(TableScanOperator.java:265)
	at io.trino.operator.Driver.processInternal(Driver.java:403)
	at io.trino.operator.Driver.lambda$process$8(Driver.java:306)
	at io.trino.operator.Driver.tryWithLock(Driver.java:709)
	at io.trino.operator.Driver.process(Driver.java:298)
	at io.trino.operator.Driver.processForDuration(Driver.java:269)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:890)
	at io.trino.execution.executor.dedicated.SplitProcessor.run(SplitProcessor.java:77)
	at io.trino.execution.executor.dedicated.TaskEntry$VersionEmbedderBridge.lambda$run$0(TaskEntry.java:201)
	at io.trino.$gen.Trino_testversion____20240926_040924_1.run(Unknown Source)
	at io.trino.execution.executor.dedicated.TaskEntry$VersionEmbedderBridge.run(TaskEntry.java:202)
	at io.trino.execution.executor.scheduler.FairScheduler.runTask(FairScheduler.java:172)
	at io.trino.execution.executor.scheduler.FairScheduler.lambda$submit$0(FairScheduler.java:159)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:76)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)
```

**Quick fix suggestion that solved the issue for me:**

```java
  if(type instanceof DateType dateType) {
      dateType.writeLong(rowBuilder, ((SqlDate) value).getDays());
      return;
  }
```

**Comment by nineinchnick** [comment]
Do you know of any public API that uses this data type? I'd add it in tests to avoid regressions. The Pet Store demo API only uses date-time.

**Comment by aleksanderlech** [comment]
Unfortunately no, I will try to create some example later. This is atomatically generated by my Spring Boot service domain looking like that:

```java
@Schema(description = "Passport issue date")
private LocalDate issueDate;
```

Which is translated into:

```json
"issueDate":{"type":"string","description":"Passport issue date","format":"date"}
```

**Comment by nineinchnick** [comment]
I'm adding another small test API using FastAPI in Python, which also supports OpenAPI 3.1. I wanted to do that for a long time now, so it's a good opportunity. I'll open a PR shortly.
