### ISSUE TITLE
Openapi integration is failing due to dependency error 

### ISSUE THREAD

**Issue by ajaytrivedi67** [nineinchnick/trino-openapi#31]
While trying to configure openapi connector with trino 402, but it is failing with below error  

`2023-10-31T03:27:54.089Z        INFO    main    io.trino.connector.StaticCatalogManager -- Loading catalog openapi --
2023-10-31T03:27:54.333Z        ERROR   main    io.trino.server.Server  io/opentelemetry/api/OpenTelemetry
java.lang.NoClassDefFoundError: io/opentelemetry/api/OpenTelemetry
        at io.airlift.http.client.HttpClientModule$HttpClientProvider.<init>(HttpClientModule.java:101)
        at io.airlift.http.client.HttpClientModule.configure(HttpClientModule.java:77)
        at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:426)
        at io.airlift.http.client.HttpClientBinder.bindHttpClient(HttpClientBinder.java:48)
        at pl.net.was.OpenApiModule.setup(OpenApiModule.java:67)
        at io.airlift.configuration.AbstractConfigurationAwareModule.configure(AbstractConfigurationAwareModule.java:47)
        at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:426)
        at com.google.inject.spi.Elements.getElements(Elements.java:113)
        at com.google.inject.spi.Elements.getElements(Elements.java:106)
        at io.airlift.configuration.ConfigurationFactory.registerConfigurationClasses(ConfigurationFactory.java:179)
        at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:216)
        at pl.net.was.OpenApiConnectorFactory.create(OpenApiConnectorFactory.java:52)
        at io.trino.connector.DefaultCatalogFactory.createConnector(DefaultCatalogFactory.java:201)
        at io.trino.connector.DefaultCatalogFactory.createCatalog(DefaultCatalogFactory.java:123)
        at io.trino.connector.LazyCatalogFactory.createCatalog(LazyCatalogFactory.java:44)
        at io.trino.connector.StaticCatalogManager.loadInitialCatalogs(StaticCatalogManager.java:139)
        at io.trino.server.Server.doStart(Server.java:139)
        at io.trino.server.Server.lambda$start$0(Server.java:88)
        at io.trino.$gen.Trino_402_e_14____20231031_032736_1.run(Unknown Source)
        at io.trino.server.Server.start(Server.java:88)
        at com.starburstdata.presto.StarburstTrinoServer.main(StarburstTrinoServer.java:46)
Caused by: java.lang.ClassNotFoundException: io.opentelemetry.api.OpenTelemetry
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
        at io.trino.server.PluginClassLoader.loadClass(PluginClassLoader.java:126)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
        ... 21 more`

Reference link:- https://github.com/nineinchnick/trino-openapi/tree/v1.3
Downloaded the plugin data from  https://github.com/nineinchnick/trino-openapi/releases/tag/v1.3

Could you the right dependency in the repo to resolve this issue?

**Comment by ajaytrivedi67** [comment]
updated

**Comment by nineinchnick** [comment]
Why have you chosen the version 1.3? It's one of the initial versions of this connector that probably is very limited in functionality and has lots of issues. It's also built using Trino 418.

The error you're getting means the OpenTelemetry libraries are missing. This is expected, because they were added in Trino 414, and you're running 402. Things you can try:
* Upgrade Trino
* Add the OpenTelemetry jars to this plugin's dir. The plugin might still not work because of incompatibilities in the SPI.
* Fork this repository and build the latest version of this plugin with an older version of Trino. This will require code changes, as there were many SPI changes since 402, but it's the most robust solution.

**Comment by nineinchnick** [comment]
I'll close this since there are no updated on it. It doesn't sound like an issue with this connector.
