### ISSUE TITLE
Trino exception with default github properties file

### ISSUE THREAD

**Issue by Angel-Asensio** [nineinchnick/trino-openapi#32]
Project built with Trino 431 and github as API:

**github.properties**
connector.name=openapi
spec-location=https://github.com/github/rest-api-description/raw/main/descriptions/api.github.com/api.github.com.json
base-uri=https://api.github.com

show tables from github.information_schema;

Table
------------------
 applicable_roles
 columns
 enabled_roles
 roles
 schemata
 table_privileges
 tables
 views
(8 rows)

Query 20231107_134059_00006_nt6xn, FINISHED, 1 node
Splits: 19 total, 19 done (100,00%)
0,35 [8 rows, 300B] [22 rows/s, 852B/s]

show tables from github.default;

Query 20231107_134415_00007_nt6xn failed: Error listing tables for catalog github: tableName is empty

and the server log:

2023-11-07T14:44:15.401+0100	ERROR	stage-scheduler	io.trino.execution.StageStateMachine	Stage 20231107_134415_00007_nt6xn.2 failed
io.trino.spi.TrinoException: Error listing tables for catalog github: tableName is empty
	at io.trino.metadata.MetadataListing.handleListingException(MetadataListing.java:349)
	at io.trino.metadata.MetadataListing.listTables(MetadataListing.java:120)
	at io.trino.connector.informationschema.InformationSchemaPageSource.addTablesRecords(InformationSchemaPageSource.java:279)
	at io.trino.connector.informationschema.InformationSchemaPageSource.buildPages(InformationSchemaPageSource.java:220)
	at io.trino.connector.informationschema.InformationSchemaPageSource.getNextPage(InformationSchemaPageSource.java:184)
	at io.trino.operator.ScanFilterAndProjectOperator$ConnectorPageSourceToPages.process(ScanFilterAndProjectOperator.java:386)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:412)
	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:261)
	at io.trino.operator.WorkProcessorUtils$YieldingProcess.process(WorkProcessorUtils.java:181)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:412)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:346)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:412)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:346)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:412)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:346)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:412)
	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:261)
	at io.trino.operator.WorkProcessorUtils$BlockingProcess.process(WorkProcessorUtils.java:207)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:412)
	at io.trino.operator.WorkProcessorUtils.lambda$flatten$6(WorkProcessorUtils.java:317)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:359)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:412)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:346)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:412)
	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:261)
	at io.trino.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:240)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:412)
	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:261)
	at io.trino.operator.WorkProcessorUtils.lambda$finishWhen$3(WorkProcessorUtils.java:255)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:412)
	at io.trino.operator.WorkProcessorSourceOperatorAdapter.getOutput(WorkProcessorSourceOperatorAdapter.java:145)
	at io.trino.operator.Driver.processInternal(Driver.java:395)
	at io.trino.operator.Driver.lambda$process$8(Driver.java:298)
	at io.trino.operator.Driver.tryWithLock(Driver.java:694)
	at io.trino.operator.Driver.process(Driver.java:290)
	at io.trino.operator.Driver.processForDuration(Driver.java:261)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:887)
	at io.trino.execution.executor.timesharing.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:187)
	at io.trino.execution.executor.timesharing.TimeSharingTaskExecutor$TaskRunner.run(TimeSharingTaskExecutor.java:565)
	at io.trino.$gen.Trino_dev____20231107_133251_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalArgumentException: tableName is empty
	at io.trino.spi.connector.SchemaUtil.checkNotEmpty(SchemaUtil.java:28)
	at io.trino.spi.connector.SchemaTableName.<init>(SchemaTableName.java:37)
	at pl.net.was.OpenApiMetadata.lambda$listTables$0(OpenApiMetadata.java:117)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at pl.net.was.OpenApiMetadata.listTables(OpenApiMetadata.java:118)
	at io.trino.tracing.TracingConnectorMetadata.listTables(TracingConnectorMetadata.java:264)
	at io.trino.metadata.MetadataManager.listTables(MetadataManager.java:521)
	at io.trino.tracing.TracingMetadata.listTables(TracingMetadata.java:314)
	at io.trino.metadata.MetadataListing.doListTables(MetadataListing.java:126)
	at io.trino.metadata.MetadataListing.listTables(MetadataListing.java:117)
	... 41 more

**Comment by nineinchnick** [comment]
Thanks for reporting this! I had a test for the github spec, but it only checked if some selected tables existed, not if all tables can be listed.
