### ISSUE TITLE
Issue with logging for JIRA catalog with openapi connector

### ISSUE THREAD

**Issue by saurabh-shinde** [nineinchnick/trino-openapi#35]
We are getting 404 error while trying to query a table from JIRA catalog. Please note that we are able to interact with APIs on JIRA server without issue.
For debugging this further, I tried enabling `openApiAuthentication.http-client.log.enabled` & `openApi.http-client.log.enabled`.
But we do not see anything logged in it, just an empty file.

```
io.airlift.http.client.UnexpectedResponseException: Expected response code to be [200, 201, 202, 203, 204, 205, 206], but was 404
	at io.airlift.http.client.JsonResponseHandler.handle(JsonResponseHandler.java:70)
	at io.airlift.http.client.jetty.JettyHttpClient.doExecute(JettyHttpClient.java:739)
	at io.airlift.http.client.jetty.JettyHttpClient.execute(JettyHttpClient.java:646)
	at pl.net.was.authentication.Authentication.getToken(Authentication.java:236)
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:181)
	at pl.net.was.authentication.Authentication.applyOAuth(Authentication.java:220)
	at pl.net.was.authentication.Authentication.lambda$applyAuthFilters$0(Authentication.java:149)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
	at pl.net.was.authentication.Authentication.lambda$applyAuthFilters$1(Authentication.java:143)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at pl.net.was.authentication.Authentication.applyAuthFilters(Authentication.java:143)
	at pl.net.was.authentication.Authentication.filterRequest(Authentication.java:113)
	at io.airlift.http.client.jetty.JettyHttpClient.applyRequestFilters(JettyHttpClient.java:828)
	at io.airlift.http.client.jetty.JettyHttpClient.execute(JettyHttpClient.java:640)
	at pl.net.was.OpenApiClient.makeRequest(OpenApiClient.java:148)
	at pl.net.was.OpenApiClient.getRows(OpenApiClient.java:95)
	at pl.net.was.OpenApiRecordSetProvider.getRecordSet(OpenApiRecordSetProvider.java:74)
	at io.trino.split.RecordPageSourceProvider.createPageSource(RecordPageSourceProvider.java:50)
	at io.trino.split.PageSourceManager.createPageSource(PageSourceManager.java:61)
	at io.trino.operator.TableScanOperator.getOutput(TableScanOperator.java:296)
	at io.trino.operator.Driver.processInternal(Driver.java:395)
	at io.trino.operator.Driver.lambda$process$8(Driver.java:298)
	at io.trino.operator.Driver.tryWithLock(Driver.java:694)
	at io.trino.operator.Driver.process(Driver.java:290)
	at io.trino.operator.Driver.processForDuration(Driver.java:261)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:887)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:187)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:555)
	at io.trino.$gen.Trino_423_e_5____20231109_061205_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by nineinchnick** [comment]
This is caused by the connector trying to get an OAuth token, even though OAuth is not configured. I'll try to fix it soon.
