### ISSUE TITLE
Type conversion failing with error

### ISSUE THREAD

**Issue by saurabh-shinde** [nineinchnick/trino-openapi#68]
While querying Jira Search API, we are getting error. Please note that API is completed successfully this time.
We are using latest version of connector(1.33) with Trino 435.
Error:
```
java.lang.ClassCastException: class com.fasterxml.jackson.databind.node.TextNode cannot be cast to class com.fasterxml.jackson.databind.node.ArrayNode (com.fasterxml.jackson.databind.node.TextNode and com.fasterxml.jackson.databind.node.ArrayNode are in unnamed module of loader io.trino.server.PluginClassLoader @7b5afde5)
	at pl.net.was.JsonTrinoConverter.convert(JsonTrinoConverter.java:140)
	at pl.net.was.OpenApiClient.convertJsonToRecord(OpenApiClient.java:462)
	at pl.net.was.OpenApiClient.convertJson(OpenApiClient.java:431)
	at pl.net.was.OpenApiClient$JsonResponseHandler.handle(OpenApiClient.java:412)
	at pl.net.was.OpenApiClient$JsonResponseHandler.handle(OpenApiClient.java:373)
	at io.airlift.http.client.jetty.JettyHttpClient.doExecute(JettyHttpClient.java:739)
	at io.airlift.http.client.jetty.JettyHttpClient.execute(JettyHttpClient.java:646)
	at pl.net.was.OpenApiClient.makeRequest(OpenApiClient.java:187)
	at pl.net.was.OpenApiClient.getRows(OpenApiClient.java:133)
	at pl.net.was.OpenApiRecordSetProvider.getRecordSet(OpenApiRecordSetProvider.java:74)
	at io.trino.split.RecordPageSourceProvider.createPageSource(RecordPageSourceProvider.java:50)
	at io.trino.split.PageSourceManager.createPageSource(PageSourceManager.java:61)
	at io.trino.operator.TableScanOperator.getOutput(TableScanOperator.java:263)
	at io.trino.operator.Driver.processInternal(Driver.java:398)
	at io.trino.operator.Driver.lambda$process$8(Driver.java:301)
	at io.trino.operator.Driver.tryWithLock(Driver.java:704)
	at io.trino.operator.Driver.process(Driver.java:293)
	at io.trino.operator.Driver.processForDuration(Driver.java:264)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:887)
	at io.trino.execution.executor.timesharing.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:187)
	at io.trino.execution.executor.timesharing.TimeSharingTaskExecutor$TaskRunner.run(TimeSharingTaskExecutor.java:565)
	at io.trino.$gen.Trino_435____20240205_074136_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by nineinchnick** [comment]
I just fixed this and finally added an integration tests with Jira Cloud. Currently, it's a single query, but I'll be adding more if there are any more issues with Jira reported.

**Comment by saurabh-shinde** [comment]
Hi,
I am seeing another issue with `project` API for JIRA. Error is due to Timestamp conversion.
```
2024-02-21T10:48:10.855Z	ERROR	stage-scheduler	io.trino.execution.StageStateMachine	Stage 20240221_104809_00015_dfqb7.0 failed
java.time.format.DateTimeParseException: Text '2023-06-01T19:26:51.422+0000' could not be parsed at index 23
	at java.base/java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2108)
	at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:2010)
	at pl.net.was.JsonTrinoConverter.convert(JsonTrinoConverter.java:131)
	at pl.net.was.OpenApiClient.convertJsonToRecord(OpenApiClient.java:466)
	at pl.net.was.OpenApiClient.convertJson(OpenApiClient.java:431)
	at pl.net.was.OpenApiClient$JsonResponseHandler.handle(OpenApiClient.java:416)
	at pl.net.was.OpenApiClient$JsonResponseHandler.handle(OpenApiClient.java:377)
	at io.airlift.http.client.jetty.JettyHttpClient.doExecute(JettyHttpClient.java:739)
	at io.airlift.http.client.jetty.JettyHttpClient.execute(JettyHttpClient.java:646)
	at pl.net.was.OpenApiClient.makeRequest(OpenApiClient.java:188)
	at pl.net.was.OpenApiClient.getRows(OpenApiClient.java:134)
	at pl.net.was.OpenApiRecordSetProvider.getRecordSet(OpenApiRecordSetProvider.java:74)
	at io.trino.split.RecordPageSourceProvider.createPageSource(RecordPageSourceProvider.java:50)
	at io.trino.split.PageSourceManager.createPageSource(PageSourceManager.java:61)
	at io.trino.operator.TableScanOperator.getOutput(TableScanOperator.java:263)
	at io.trino.operator.Driver.processInternal(Driver.java:398)
	at io.trino.operator.Driver.lambda$process$8(Driver.java:301)
	at io.trino.operator.Driver.tryWithLock(Driver.java:704)
	at io.trino.operator.Driver.process(Driver.java:293)
	at io.trino.operator.Driver.processForDuration(Driver.java:264)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:887)
	at io.trino.execution.executor.timesharing.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:187)
	at io.trino.execution.executor.timesharing.TimeSharingTaskExecutor$TaskRunner.run(TimeSharingTaskExecutor.java:565)
	at io.trino.$gen.Trino_435____20240221_104458_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by nineinchnick** [comment]
Yes, please create another issue with reproduction steps (the query you're running). I checked a few tables starting with `rest_api_3_project` but they all return data correctly.
