### ISSUE TITLE
Casting error from VariableWidthBlock to ArrayBlock for array(varchar) column

### ISSUE THREAD

**Issue by nmkarvekar** [nineinchnick/trino-openapi#79]
Suppose we have field of type array(varchar) , when we try to use that field in where clause in sql query something like this:

select * from mycatalog.default.query where returned_fields=ARRAY['name','address']

we see below error:
io.trino.spi.block.VariableWidthBlock cannot be cast to class io.trino.spi.block.ArrayBlock (io.trino.spi.block.VariableWidthBlock and io.trino.spi.block.ArrayBlock

here is the stack trace:
at io.trino.spi.type.ArrayType.getObject(ArrayType.java:262)
at pl.net.was.JsonTrinoConverter.convert(JsonTrinoConverter.java:321)
at pl.net.was.OpenApiClient.serializeMap(OpenApiClient.java:334)
at pl.net.was.OpenApiClient.getRows(OpenApiClient.java:129)
at pl.net.was.OpenApiRecordSetProvider.getRecordSet(OpenApiRecordSetProvider.java:75)
at io.trino.split.RecordPageSourceProvider.createPageSource(RecordPageSourceProvider.java:50)
at io.trino.split.PageSourceManager.createPageSource(PageSourceManager.java:61)
at io.trino.operator.TableScanOperator.getOutput(TableScanOperator.java:263)
at io.trino.operator.Driver.processInternal(Driver.java:398)
at io.trino.operator.Driver.lambda$process$8(Driver.java:301)
at io.trino.operator.Driver.tryWithLock(Driver.java:704)
at io.trino.operator.Driver.process(Driver.java:293)

**Comment by nineinchnick** [comment]
I need more info to be able to reproduce this - what's the spec you're using?

**Comment by nmkarvekar** [comment]
we can use below spec:

```
openapi: 3.0.1
info:
  title: test Service
  contact:
    name: test
    email: test@test.com
  version: '2.0'
servers:
  - url: /api/test/v2/
security:
  - Authorization: []
paths:
  /employee:
    post:
      operationId: employee
      parameters:
        - name: request-id
          in: header
          description: Request Id
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Employee'
        required: true       
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: string
components:
  schemas:
    Employee:
      type: object
      properties:
        name:
          type: string
        address:
          type: string
        returnedFields:
          type: array
          items:
            type: string  
  securitySchemes:
    Authorization:
      type: http
      scheme: bearer
      bearerFormat: Authorization
```


If we hit the query like:

**select * from mycatalog.default.employee where request_id='p1' and name='nk' and address='add' and  returned_fields = ARRAY['id']**

we see this error:
**java.lang.ClassCastException: class io.trino.spi.block.VariableWidthBlock cannot be cast to class io.trino.spi.block.ArrayBlock**

**Comment by nineinchnick** [comment]
Fixed in eb4055462b5b8e55f92f73dcb3f6c39cb80da88d

**Comment by nineinchnick** [comment]
Thanks a lot for reporting this!

**Comment by nmkarvekar** [comment]
@nineinchnick I checked the fix with below query:

select * from mycatalog.default.employee where request_id='p1' and name='nk' and address='add' and returned_fields = ARRAY['id']


I see below error:

java.lang.NullPointerException: Cannot invoke "pl.net.was.OpenApiColumn.getSourceName()" because "column" is null
	at pl.net.was.OpenApiClient.serializeMap(OpenApiClient.java:342)
	at pl.net.was.OpenApiClient.getRows(OpenApiClient.java:129)
	at pl.net.was.OpenApiRecordSetProvider.getRecordSet(OpenApiRecordSetProvider.java:74)
	at io.trino.split.RecordPageSourceProvider.createPageSource(RecordPageSourceProvider.java:50)
	at io.trino.split.PageSourceManager.createPageSource(PageSourceManager.java:61)
	at io.trino.operator.TableScanOperator.getOutput(TableScanOperator.java:263)
	at io.trino.operator.Driver.processInternal(Driver.java:398)
	at io.trino.operator.Driver.lambda$process$8(Driver.java:301)
	at io.trino.operator.Driver.tryWithLock(Driver.java:704)
	at io.trino.operator.Driver.process(Driver.java:293)
	at io.trino.operator.Driver.processForDuration(Driver.java:264)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:887)
	at io.trino.execution.executor.dedicated.SplitProcessor.run(SplitProcessor.java:76)
	at io.trino.execution.executor.dedicated.TaskEntry$VersionEmbedderBridge.lambda$run$0(TaskEntry.java:191)
	at io.trino.$gen.Trino_439____20240417_063357_2.run(Unknown Source)
	at io.trino.execution.executor.dedicated.TaskEntry$VersionEmbedderBridge.run(TaskEntry.java:192)
	at io.trino.execution.executor.scheduler.FairScheduler.runTask(FairScheduler.java:174)
	at io.trino.execution.executor.scheduler.FairScheduler.lambda$submit$0(FairScheduler.java:161)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:76)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
